version: '3.8'

services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    volumes:
      - laravel_storage:/var/www/html/storage
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      # Application Environment
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}

      # Localization
      - APP_LOCALE=${APP_LOCALE}
      - APP_FALLBACK_LOCALE=${APP_FALLBACK_LOCALE}
      - APP_FAKER_LOCALE=${APP_FAKER_LOCALE}

      # Maintenance
      - APP_MAINTENANCE_DRIVER=${APP_MAINTENANCE_DRIVER}

      # PHP CLI
      - PHP_CLI_SERVER_WORKERS=${PHP_CLI_SERVER_WORKERS}

      # Security
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS}

      # Logging
      - LOG_CHANNEL=${LOG_CHANNEL}
      - LOG_STACK=${LOG_STACK}
      - LOG_DEPRECATIONS_CHANNEL=${LOG_DEPRECATIONS_CHANNEL}
      - LOG_LEVEL=${LOG_LEVEL}

      # Database Configuration
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

      # Session Configuration
      - SESSION_DRIVER=${SESSION_DRIVER}
      - SESSION_LIFETIME=${SESSION_LIFETIME}
      - SESSION_ENCRYPT=${SESSION_ENCRYPT}
      - SESSION_PATH=${SESSION_PATH}
      - SESSION_DOMAIN=${SESSION_DOMAIN}

      # Broadcast, Filesystem, and Queue
      - BROADCAST_CONNECTION=${BROADCAST_CONNECTION}
      - FILESYSTEM_DISK=${FILESYSTEM_DISK}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}

      # Cache
      - CACHE_STORE=${CACHE_STORE}

      # Memcached
      - MEMCACHED_HOST=${MEMCACHED_HOST}

      # Redis
      - REDIS_CLIENT=${REDIS_CLIENT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}

      # Mail
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_SCHEME=${MAIL_SCHEME}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - VITE_APP_NAME=${VITE_APP_NAME}
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=root" ]
      interval: 10s
      timeout: 5s
      retries: 3
  redis:
    image: redis:latest
    container_name: laravel_redis
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin
    restart: always

volumes:
  mysql_data:
  laravel_storage:
